site_name: Project Documentation
site_author: Opoloo
repo_url: https://github.com/opoloo/middleman-template
site_url: https://opoloo.github.io/middleman-template
theme_dir: ./mkdocs-themes/docoloo

site_dir: doc_build
docs_dir: docs

extra_css:
#  - stylesheets/base.css
extra_javascript:
extra:
  version: 0.1
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
